# -*- coding: utf-8 -*-
"""DeploymentP1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b27hWzpW-ZqXjdIQiKkyzNtbawc1iTFc
"""

print ("Coba Deployment Pertemuan 1")

